version: '3.8'  
services:  
  db:  
    container_name: pg_container1  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: prueba2  
    ports:  
      - "5433:5432" 